version: '2.1'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8003:80
    volumes:
      - ./:/app

  php:
    build:
      context: ./docker/php
      args:
        DOCKER_UID: 1000
        DOCKER_GID: 1000
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    volumes:
      - ./:/app

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'lara_react'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./docker/mysql-vol:/var/lib/mysql
    ports:
      - 13308:3306

  composer:
    image: composer:1.9
    volumes:
      - ./:/app
    command: echo true

volumes:
  mysql-vol:
    driver: local
